[package]
name = "broadcast-server"
version = "0.1.0"
edition = "2021"

[dependencies]
aper = "0.1.3"
serde = "1.0.133"
serde_json = "1.0.74"
simple-websockets = "0.1.4"
state = { path = "../state" }
